### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Ant-VAV** [Koleok/jest-coverage-ratchet#4]
Hello!
I'm trying to run `jest-coverage-ratchet` but it doesn't want to modify my `package.json` file.
File `coverage-summary.json` is created.

Here my test project: https://github.com/Ant-VAV/jest_tests

Can you explain what I do wrong?

**Comment by Koleok** [comment]
Hi @Ant-VAV I submitted a PR to that example repo showing some usage. The DX on this isn't really well thought out or anything it was just the result of be needing to use it on a project. I would love to improve that element of it so if you have any suggestions or PRs I am all 👂 s.

Otherwise at **some** point i will improve ease of use.

**Comment by Ant-VAV** [comment]
Wow, it works!
Thank you a lot!
